<?php
/**
 * Copyright © 2019 V2Agency . All rights reserved.
 * 
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $this->helper('V2Agency\Callforprice\Helper\Data');
$_prd 					= $product;
$itemSelector 			= '.product-item';
$priceElementSelector	= '.price-box';
$cartButtonElementSelector	= '.tocart';
$classActionButton			= '.product-item-actions .actions-primary';
$loadformurl = $helper->loadformurl();
$canshow = $helper->showCallForPriceButton($_prd);
$enableModule = $helper->enableModule();
$buttonTitle = $helper->getButtonTitle();
$productType = $_prd->getTypeID();
if($canshow == 1 && $enableModule): ?>
	<div class="callforprice-product" id="productId_<?php echo $_prd->getId() ?>"></div>
    <script type="text/javascript">
		require(['jquery','mage/translate','callforprice'], function ($, mage, callforpriceConfig) {
			var callforpriceConfig = {
				"productId": <?php echo $_prd->getId() ?>,
				"buttonTitle": '<?php echo $buttonTitle ?>',
				"loadformurl": '<?php echo $loadformurl ?>',
				"itemSelector" : '<?php echo $itemSelector ?>',
				"priceElementSelector": '<?php echo $priceElementSelector ?>',
				"cartButtonElementSelector": '<?php echo $cartButtonElementSelector ?>',
				"modeView": '<?php echo $helper->getActionHandle() ?>',
				"classActionButton" : '<?php echo $classActionButton ?>',
				"productType" : '<?php echo $productType ?>'
			}
			$('.callforprice-product#productId_<?php echo $_prd->getId() ?>').callforprice(callforpriceConfig);
		});
    </script>
<?php endif; ?>