<?php
/**
 * Copyright © 2019 V2Agency . All rights reserved.
 * 
 */
 $helper 		  = $this->helper('V2Agency\Callforprice\Helper\Data');
 $submiturl 	  = $helper->submitformurl();
 $objectManager	  = \Magento\Framework\App\ObjectManager::getInstance();
 $customerSession = $objectManager->get('Magento\Customer\Model\Session');
 $imageBlock	  = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
 $producthelper	  = $this->helper('Magento\Catalog\Helper\Output');
?>
<div class="callprice_request_form">
    <form action="<?php echo $block->getUrl('callforprice/index/submit') ?>" name="cp_form" id="cp_form" method="post">
		<div class="fieldset">
			<ul class="form-list products-list">
				<li class="fields">
					<div class="field" style="float: left;">
						<a href="<?php echo $product->getProductUrl(); ?>" style="width: 15%;margin: 0 10px 10px 0" title="<?php echo $product->getName() ?>" class="product-image">
							<?php echo $imageBlock->getImage($product, 'category_page_list')->toHtml() ?>
						</a>
						<div class="product-shop" style="">
							<div class="product-name">
								<span style="font-size:25px"><?php echo $product->getName() ?></span>
							</div>
							<p><?php 
									$des = $producthelper->productAttribute($product, $product->getShortDescription(), 'short_description');
									echo $des;
							?></p>
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field" style="clear: both;">
						<label class="required" for="name"><?php echo __('Name') ?> <em>*</em></label>
						<div class="input-box">
							<input id="name" name="name" type="text" class="input-text required-entry" value="<?php echo $customerSession->getCustomer()->getName() ?>" data-validate="{required:true}"/>
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">              
						<label class="required" for="email"><?php echo __('Email') ?> <em>*</em></label>
						<div class="input-box">
							<input id="email" name="email" type="text" class="input-text" value="<?php echo $customerSession->getCustomer()->getEmail() ?>" data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label class="required" for="telephone"><?php echo __('Phone') ?> <em>*</em></label>
						<div class="input-box">
							<input id="telephone" name="telephone" type="text" class="input-text required-entry " value="<?php echo $customerSession->getCustomer()->getTelephone() ?>" data-validate="{required:true}"/>
						</div>
					</div>
				</li>
				<li class="fields">
					<div class="field">
						<label class="required" for="comment"><?php echo __('Comments') ?> <em>*</em></label>
						<div class="input-box">
							<textarea rows="3" cols="5" class="required-entry input-text" title="details" id="details" name="details"></textarea>
						</div>
					</div>
				</li>
				<?php if($helper->getCapchaStatus()): ?>
				<li class="fields">
					<div class="field">
						<div class="g-recaptcha" data-sitekey="<?php echo $helper->getCapchaSiteId() ?>"></div>
						<script type="text/javascript"
								src="https://www.google.com/recaptcha/api.js?hl=en">
						</script>
					</div>
				</li>
				<?php endif; ?>
				<li class="fields actions">
					<div>
						<button type="submit" style="float: left" class="button"><span><span><?php echo __('Submit Quote Request') ?></span></span></button>
						<img class="img_loader_callforprice" id="img_loader_callforprice" src="<?php echo $block->getViewFileUrl('V2Agency_Callforprice::images/ajax-loader.gif'); ?>" alt="" style="display: none;float: left;margin: 11px;">
					</div>
				</li>
			</ul>
		</div>
        <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>"/>
    </form>
    <b style="color: #2C26EC" id="messageresponse" style="display: none;" class="messageresponse"></b>
</div>
<script type="text/javascript">
    //<![CDATA[
	require([
        "jquery",
        "mage/mage",
		"jquery/validate",
		'mage/translate'
    ], function($){
		/* $.mage.__(''); */
        var dataForm = $('#cp_form');
        dataForm.mage('validation', {
			submitHandler: function (form) {
				$('#img_loader_callforprice').show();
				<?php if($helper->getCapchaStatus()): ?>
				if (grecaptcha.getResponse() == ""){
					alert($.mage.__('You must be verify capcha before submit request !'));
					$('#img_loader_callforprice').hide();
					return false;
				}
				<?php endif; ?>
				$.ajax({
					url: form.action,
					type: 'POST',
					dataType: 'json',
					data: $(this.currentForm).serialize(),
					success: function(result){
						var displayString = result.message;
						if(result.success) {
							$('#cp_form').hide();
							$('#img_loader_callforprice').hide();
							$('#messageresponse').show();
							$('#messageresponse').html('<ul class="messages"><li class="success-msg"><ul><li><span>'+displayString+'</span></li></ul></li></ul>');
							setTimeout(function(){ $.fancybox.close(); }, 4000);
						}
						else
						{
							$('#cp_form').hide();
							$('#img_loader_callforprice').hide();
							$('#messageresponse').show();
							$('#messageresponse').html('<ul class="messages"><li class="error-msg"><ul><li><span>'+displayString+'</span></li></ul></li></ul>');
						}
					}
				});
				return false;
			}
		});
    });
    //]]>
</script>